import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import React from 'react';
import { getDesignClasses } from '../../utils/designSystem';
import { trackClick } from '../../services/analytics';
// --- Helper Functions & Components ---
const scrollToSection = (id) => {
    const element = document.getElementById(id);
    if (element) {
        element.scrollIntoView({ behavior: 'smooth' });
    }
};
const MapEmbed = ({ address, className = "", heightClass = "h-64" }) => (_jsx("div", { className: `w-full ${heightClass} overflow-hidden shadow-sm bg-gray-100 ${className}`, children: _jsx("iframe", { width: "100%", height: "100%", frameBorder: "0", style: { border: 0 }, src: `https://maps.google.com/maps?q=${encodeURIComponent(address)}&t=&z=15&ie=UTF8&iwloc=&output=embed`, allowFullScreen: true, loading: "lazy", title: `Mapa para ${address}` }) }));
export const WhatsAppButton = ({ phone, landingPageId }) => {
    if (!phone)
        return null;
    // Clean phone for link (remove non-numeric chars)
    const cleanPhone = phone.replace(/\D/g, '');
    const handleClick = (e) => {
        e.stopPropagation();
        if (landingPageId) {
            try {
                trackClick(landingPageId, 'WhatsApp Flutuante', 'whatsapp_floating', {
                    referrer: typeof document !== 'undefined' ? document.referrer || undefined : undefined,
                    user_agent: typeof navigator !== 'undefined' ? navigator.userAgent : undefined,
                });
            }
            catch (error) {
                console.error('Erro ao registrar clique no WhatsApp flutuante:', error);
            }
        }
    };
    return (_jsxs("a", { href: `https://wa.me/55${cleanPhone}`, target: "_blank", rel: "noopener noreferrer", className: "fixed bottom-6 right-6 z-50 bg-[#25D366] hover:bg-[#20bd5a] text-white p-4 rounded-full shadow-2xl transition-all duration-300 hover:scale-110 group flex items-center gap-2 animate-fade-in", "aria-label": "Falar no WhatsApp", onClick: handleClick, children: [_jsx("svg", { className: "w-8 h-8", fill: "currentColor", viewBox: "0 0 24 24", xmlns: "http://www.w3.org/2000/svg", children: _jsx("path", { d: "M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413Z" }) }), _jsx("span", { className: "hidden md:block font-bold pr-2", children: "Agendar" })] }));
};
// --- Existing Components ---
export const Navbar = ({ design, briefing, visibility, layoutVariant = 1, content, landingPageId }) => {
    const { p, s } = getDesignClasses(design);
    if (!briefing || !visibility)
        return null;
    const handleLinkClick = (e, id) => {
        e.preventDefault();
        scrollToSection(id);
    };
    const handleCtaClick = () => {
        if (landingPageId) {
            try {
                trackClick(landingPageId, 'CTA Navbar - Agendar', 'navbar', {
                    referrer: typeof document !== 'undefined' ? document.referrer || undefined : undefined,
                    user_agent: typeof navigator !== 'undefined' ? navigator.userAgent : undefined,
                });
            }
            catch (error) {
                console.error('Erro ao registrar clique no CTA do Navbar:', error);
            }
        }
        if (content.contactPhone) {
            const cleanPhone = content.contactPhone.replace(/\D/g, '');
            window.open(`https://wa.me/55${cleanPhone}`, '_blank');
        }
        else {
            scrollToSection('contact');
        }
    };
    const CrmBadge = () => (_jsxs("div", { className: "flex flex-col md:flex-row md:items-center md:gap-2", children: [_jsx("span", { className: "font-bold", children: briefing.name }), briefing.crm && (_jsxs("span", { className: "text-[10px] uppercase tracking-wider opacity-70 bg-gray-100 px-1 rounded text-gray-600 font-sans border border-gray-200", children: ["CRM/", briefing.crmState || 'UF', " ", briefing.crm] }))] }));
    if (layoutVariant === 5) {
        return (_jsxs("nav", { className: `py-8 px-6 md:px-12 flex flex-col md:flex-row justify-between items-center bg-white border-b-2 border-black`, children: [_jsx("div", { className: `text-2xl font-serif font-bold tracking-tighter ${p.primary} text-center md:text-left mb-4 md:mb-0`, children: _jsx(CrmBadge, {}) }), _jsxs("div", { className: "flex gap-4 md:gap-8 text-xs font-bold uppercase tracking-widest", children: [visibility.about && _jsx("button", { onClick: (e) => handleLinkClick(e, 'about'), className: "hover:underline", children: "Sobre" }), visibility.services && _jsx("button", { onClick: (e) => handleLinkClick(e, 'services'), className: "hover:underline", children: "Servi\u00E7os" }), _jsx("button", { onClick: handleCtaClick, className: "border px-4 py-1 border-black cursor-pointer hover:bg-black hover:text-white transition-colors", children: "Agendar" })] })] }));
    }
    if (layoutVariant === 2) {
        return (_jsx("div", { className: "flex justify-center pt-6 sticky top-0 z-50 pointer-events-none px-4", children: _jsxs("nav", { className: `pointer-events-auto px-6 py-3 rounded-full flex items-center justify-between md:justify-start gap-4 md:gap-6 bg-white/80 backdrop-blur-lg border border-white/50 shadow-lg w-full md:w-auto`, children: [_jsx("div", { className: `font-bold ${p.primary} truncate`, children: _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-sm md:text-base", children: briefing.name }), briefing.crm && _jsxs("span", { className: "hidden md:inline text-[9px] text-gray-400 font-normal border px-1 rounded", children: ["CRM ", briefing.crm] })] }) }), _jsxs("div", { className: "hidden md:flex gap-4 text-sm text-gray-600", children: [visibility.services && _jsx("button", { onClick: (e) => handleLinkClick(e, 'services'), className: "hover:text-black", children: "Servi\u00E7os" }), visibility.testimonials && _jsx("button", { onClick: (e) => handleLinkClick(e, 'testimonials'), className: "hover:text-black", children: "Depoimentos" })] }), _jsx("button", { onClick: handleCtaClick, className: `px-4 py-1.5 text-xs font-bold text-white rounded-full ${p.accent} flex-shrink-0`, children: "Agendar" })] }) }));
    }
    return (_jsxs("nav", { className: `py-6 px-6 md:px-12 flex justify-between items-center sticky top-0 z-20 bg-white/90 backdrop-blur-md border-b ${p.border}`, children: [_jsxs("div", { className: `text-lg font-bold tracking-tight ${p.primary} flex items-center gap-2`, children: [_jsx("div", { className: `w-3 h-3 ${s.bg} rounded-full` }), _jsx(CrmBadge, {})] }), _jsxs("div", { className: "hidden md:flex gap-8 text-sm font-medium text-gray-500", children: [visibility.about && _jsx("button", { onClick: (e) => handleLinkClick(e, 'about'), className: `hover:${s.text} transition-colors`, children: "Sobre" }), visibility.services && _jsx("button", { onClick: (e) => handleLinkClick(e, 'services'), className: `hover:${s.text} transition-colors`, children: "Especialidades" }), visibility.testimonials && _jsx("button", { onClick: (e) => handleLinkClick(e, 'testimonials'), className: `hover:${s.text} transition-colors`, children: "Depoimentos" })] }), _jsx("button", { onClick: handleCtaClick, className: `px-4 py-2 md:px-5 md:py-2.5 text-sm font-semibold text-white shadow-lg shadow-${design.colorPalette}-500/20 transition-all hover:-translate-y-0.5 ${p.accent} ${p.accentHover}`, children: "Agendar" })] }));
};
export const ServicesSection = ({ content, design, layoutVariant = 1 }) => {
    const { p, s, t, r } = getDesignClasses(design);
    if (layoutVariant === 5) {
        return (_jsx("section", { id: "services", className: "py-24 px-6 md:px-12 bg-white", children: _jsxs("div", { className: "max-w-4xl mx-auto", children: [_jsx("h2", { className: `text-xs font-bold uppercase tracking-widest mb-12 border-b border-black pb-4 ${s.text}`, children: "Especialidades" }), _jsx("div", { className: "space-y-12", children: content.services.map((service, idx) => (_jsxs("div", { className: "group cursor-pointer", children: [_jsxs("h3", { className: `text-2xl md:text-5xl font-serif font-light mb-4 group-hover:pl-4 transition-all duration-300 ${p.primary}`, children: [_jsxs("span", { className: "text-sm align-top mr-4 text-gray-400 font-sans font-bold", children: ["0", idx + 1] }), service.title] }), _jsx("p", { className: "text-gray-500 max-w-xl ml-10 pl-4 border-l border-gray-200 text-sm md:text-base", children: service.description })] }, idx))) })] }) }));
    }
    if (layoutVariant === 4) {
        return (_jsx("section", { id: "services", className: `py-20 px-6 ${p.softBg}`, children: _jsxs("div", { className: "max-w-6xl mx-auto", children: [_jsxs("div", { className: "mb-12 flex items-end gap-4", children: [_jsx("h2", { className: `text-3xl md:text-4xl font-bold ${p.primary}`, children: "Servi\u00E7os" }), _jsx("div", { className: `h-1 flex-1 ${s.bg}` })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-1", children: content.services.map((service, idx) => (_jsxs("div", { className: `bg-white p-8 md:p-10 border-2 border-transparent hover:border-black transition-all duration-300 group`, children: [_jsxs("span", { className: `text-4xl md:text-5xl font-black text-gray-100 group-hover:${s.text} transition-colors`, children: [idx + 1, "."] }), _jsx("h3", { className: "text-xl font-bold mt-4 mb-2", children: service.title }), _jsx("p", { className: "text-sm text-gray-500", children: service.description })] }, idx))) })] }) }));
    }
    if (layoutVariant === 2) {
        return (_jsxs("section", { id: "services", className: `py-24 px-6 relative overflow-hidden bg-gradient-to-b ${p.gradient}`, children: [_jsx("div", { className: `absolute top-1/4 left-10 w-64 h-64 ${s.bg} opacity-10 blur-3xl rounded-full` }), _jsx("div", { className: `absolute bottom-1/4 right-10 w-80 h-80 ${p.accent} opacity-10 blur-3xl rounded-full` }), _jsxs("div", { className: "max-w-7xl mx-auto relative z-10", children: [_jsxs("div", { className: "text-center mb-16", children: [_jsx("span", { className: `text-xs font-bold uppercase tracking-wider ${s.text} mb-2 block`, children: "O que oferecemos" }), _jsx("h2", { className: `text-3xl md:text-4xl font-bold ${p.primary}`, children: content.servicesTitle })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-6", children: content.services.map((service, idx) => (_jsxs("div", { className: `bg-white/60 backdrop-blur-md p-8 border border-white/50 shadow-lg hover:shadow-xl transition-all duration-300 hover:-translate-y-2 ${r.box}`, children: [_jsx("div", { className: `w-12 h-12 rounded-2xl ${p.accent} bg-opacity-10 flex items-center justify-center mb-6 text-2xl`, children: idx === 0 ? '🔬' : idx === 1 ? '💊' : '🩺' }), _jsx("h3", { className: `text-xl font-bold mb-3 ${p.primary}`, children: service.title }), _jsx("p", { className: "text-gray-600 text-sm leading-relaxed", children: service.description })] }, idx))) })] })] }));
    }
    return (_jsx("section", { id: "services", className: `py-24 px-6 md:px-12 ${p.softBg}`, children: _jsxs("div", { className: "max-w-7xl mx-auto", children: [_jsxs("div", { className: "text-center max-w-3xl mx-auto mb-20", children: [_jsx("h2", { className: `text-3xl md:text-4xl mb-6 ${p.primary} ${t.head}`, children: content.servicesTitle }), _jsx("div", { className: `w-24 h-1 mx-auto ${s.bg} rounded-full opacity-40` })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-8", children: content.services.map((service, idx) => (_jsxs("div", { className: `group bg-white p-8 md:p-10 border ${p.border} ${r.box} hover:shadow-2xl hover:shadow-gray-200/50 transition-all duration-300 relative overflow-hidden`, children: [_jsx("div", { className: `absolute top-0 right-0 w-32 h-32 ${p.surface} rounded-bl-full -mr-8 -mt-8 transition-transform group-hover:scale-110` }), _jsx("div", { className: `relative w-14 h-14 flex items-center justify-center mb-8 text-2xl ${s.light} ${s.text} ${r.btn}`, children: idx === 0 ? '✦' : idx === 1 ? '✚' : '★' }), _jsx("h3", { className: `text-xl font-bold mb-4 relative z-10 ${p.primary}`, children: service.title }), _jsx("p", { className: "text-gray-500 leading-relaxed relative z-10", children: service.description })] }, idx))) })] }) }));
};
export const AboutSection = ({ content, design, layoutVariant = 1, aboutPhotoUrl }) => {
    const { p, s, t, r } = getDesignClasses(design);
    const photoSrc = aboutPhotoUrl || "https://picsum.photos/seed/doctor_work/800/800";
    if (layoutVariant === 4) {
        return (_jsx("section", { id: "about", className: `border-y-2 border-black`, children: _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2", children: [_jsxs("div", { className: `p-8 md:p-24 ${p.surface} flex flex-col justify-center order-2 md:order-1`, children: [_jsx("h2", { className: `text-3xl md:text-4xl font-bold mb-8 uppercase tracking-tight`, children: content.aboutTitle }), _jsx("p", { className: "text-base md:text-lg font-medium leading-relaxed", children: content.aboutBody }), _jsxs("div", { className: "mt-12 flex gap-8", children: [_jsxs("div", { children: [_jsx("span", { className: "block text-3xl font-black", children: "15+" }), _jsx("span", { className: "text-xs uppercase", children: "Anos" })] }), _jsxs("div", { children: [_jsx("span", { className: "block text-3xl font-black", children: "5k" }), _jsx("span", { className: "text-xs uppercase", children: "Pacientes" })] })] })] }), _jsx("div", { className: "h-64 md:h-full min-h-[300px] md:min-h-[400px] order-1 md:order-2", children: _jsx("img", { src: photoSrc, className: "w-full h-full object-cover grayscale contrast-125", alt: "About" }) })] }) }));
    }
    if (layoutVariant === 3) {
        return (_jsx("section", { id: "about", className: "py-24 px-6 overflow-hidden", children: _jsxs("div", { className: "max-w-6xl mx-auto relative", children: [_jsx("div", { className: `absolute top-0 right-0 w-full md:w-2/3 h-full ${p.surface} rounded-l-none md:rounded-l-[100px] -z-10` }), _jsxs("div", { className: "flex flex-col md:flex-row items-center gap-12 md:gap-16", children: [_jsx("div", { className: "w-full md:w-1/2", children: _jsxs("div", { className: "relative", children: [_jsx("div", { className: `absolute inset-0 ${s.bg} rounded-[2rem] rotate-3 opacity-20` }), _jsx("img", { src: photoSrc, className: `relative rounded-[2rem] shadow-xl w-full h-96 md:h-auto object-cover rotate-[-2deg] hover:rotate-0 transition-transform duration-500`, alt: "About" })] }) }), _jsxs("div", { className: "w-full md:w-1/2 text-center md:text-left", children: [_jsx("h2", { className: `text-3xl md:text-4xl font-bold mb-6 ${p.primary}`, children: content.aboutTitle }), _jsx("p", { className: "text-gray-600 text-lg leading-relaxed mb-8", children: content.aboutBody })] })] })] }) }));
    }
    return (_jsx("section", { id: "about", className: `py-24 px-6 md:px-12 ${p.surface} relative overflow-hidden`, children: _jsxs("div", { className: "max-w-6xl mx-auto flex flex-col md:flex-row gap-12 md:gap-16 items-center", children: [_jsx("div", { className: "w-full md:w-1/2 order-2 md:order-1", children: _jsxs("div", { className: "space-y-8", children: [_jsx("h2", { className: `text-3xl md:text-5xl ${t.head} ${p.primary}`, children: content.aboutTitle }), _jsx("div", { className: `prose prose-lg text-gray-600 ${t.body}`, children: _jsx("p", { children: content.aboutBody }) }), ((content.aboutExperienceLabel && content.aboutExperienceValue) || (content.aboutPatientsLabel && content.aboutPatientsValue)) && (_jsxs("div", { className: "grid grid-cols-2 gap-8 pt-8 border-t border-gray-200/50", children: [content.aboutExperienceLabel && content.aboutExperienceValue && (_jsxs("div", { children: [_jsx("span", { className: `block text-4xl font-bold mb-1 ${s.text}`, children: content.aboutExperienceValue }), _jsx("span", { className: "text-xs font-bold uppercase tracking-wider text-gray-400", children: content.aboutExperienceLabel })] })), content.aboutPatientsLabel && content.aboutPatientsValue && (_jsxs("div", { children: [_jsx("span", { className: `block text-4xl font-bold mb-1 ${s.text}`, children: content.aboutPatientsValue }), _jsx("span", { className: "text-xs font-bold uppercase tracking-wider text-gray-400", children: content.aboutPatientsLabel })] }))] }))] }) }), _jsxs("div", { className: "w-full md:w-1/2 order-1 md:order-2 relative h-64 md:h-auto", children: [_jsx("div", { className: `absolute inset-0 border-2 ${p.border} transform translate-x-4 translate-y-4 ${r.box}` }), _jsx("img", { src: photoSrc, alt: "Consult\u00F3rio", className: `relative w-full h-full object-cover shadow-xl grayscale hover:grayscale-0 transition-all duration-700 ${r.box}` })] })] }) }));
};
export const TestimonialsSection = ({ content, design, layoutVariant = 1, isEditorMode, hasCustomTestimonials, visibility }) => {
    const { p, s, t, r } = getDesignClasses(design);
    // Verificar se há depoimentos fake (ilustrativos)
    const hasFakeTestimonials = isEditorMode &&
        visibility?.testimonials &&
        content.testimonials &&
        content.testimonials.length > 0 &&
        !hasCustomTestimonials;
    // Componente de aviso discreto
    const TestimonialWarning = () => {
        if (!hasFakeTestimonials)
            return null;
        return (_jsx("div", { className: "mb-8 max-w-3xl mx-auto", children: _jsx("div", { className: "bg-amber-50/50 border border-amber-200/50 rounded-lg p-3 text-xs text-amber-700", children: _jsxs("p", { children: ["Os depoimentos exibidos aqui s\u00E3o apenas ilustrativos e n\u00E3o aparecer\u00E3o para os visitantes da sua p\u00E1gina enquanto voc\u00EA n\u00E3o adicionar depoimentos reais de seus pacientes. Para isso, clique em ", _jsx("strong", { children: "\"Editar P\u00E1gina\"" }), " ou, se preferir, deixe para fazer em outro momento."] }) }) }));
    };
    if (layoutVariant === 5) {
        return (_jsx("section", { id: "testimonials", className: "py-24 md:py-32 px-6 bg-stone-50 text-center", children: _jsxs("div", { className: "max-w-3xl mx-auto", children: [_jsx("h2", { className: `text-center text-3xl md:text-4xl mb-8 ${t.head} ${p.primary}`, children: "Hist\u00F3rias de Sucesso" }), _jsx(TestimonialWarning, {}), _jsx("div", { className: "text-6xl font-serif text-gray-300 mb-8", children: "\"" }), _jsx("p", { className: "text-2xl md:text-4xl font-serif leading-tight mb-10 text-gray-800", children: content.testimonials[0]?.text }), _jsxs("cite", { className: "not-italic font-sans text-sm font-bold uppercase tracking-widest text-gray-500", children: ["\u2014 ", content.testimonials[0]?.name] }), _jsx("p", { className: "text-[10px] text-gray-400 mt-2 uppercase", children: "Relato de paciente - Resultados individuais podem variar" })] }) }));
    }
    if (layoutVariant === 2) {
        return (_jsx("section", { id: "testimonials", className: `py-20 px-6 ${p.softBg}`, children: _jsxs("div", { className: "max-w-7xl mx-auto", children: [_jsx("h2", { className: "text-center text-3xl font-bold mb-12", children: "O que dizem nossos pacientes" }), _jsx(TestimonialWarning, {}), _jsx("div", { className: "flex flex-col md:flex-row gap-6 overflow-x-auto pb-8 snap-x", children: content.testimonials.map((testi, idx) => (_jsxs("div", { className: `flex-1 min-w-[280px] snap-center bg-white p-8 rounded-2xl shadow-lg border border-gray-100`, children: [_jsx("div", { className: "flex items-center gap-1 text-yellow-400 mb-4", children: "\u2605\u2605\u2605\u2605\u2605" }), _jsxs("p", { className: "text-gray-600 mb-6", children: ["\"", testi.text, "\""] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: `w-10 h-10 rounded-full ${p.accent} flex items-center justify-center text-white font-bold`, children: testi.name[0] }), _jsxs("div", { children: [_jsx("p", { className: "font-bold text-sm", children: testi.name }), _jsx("p", { className: "text-xs text-gray-400", children: "Paciente Verificado" })] })] })] }, idx))) }), _jsx("p", { className: "text-center text-xs text-gray-400 mt-4", children: "* Relatos reais. N\u00E3o garantimos os mesmos resultados para todos os pacientes." })] }) }));
    }
    return (_jsx("section", { id: "testimonials", className: "py-24 px-6 md:px-12 bg-white", children: _jsxs("div", { className: "max-w-5xl mx-auto", children: [_jsx("h2", { className: `text-center text-3xl md:text-4xl mb-4 ${t.head} ${p.primary}`, children: "Hist\u00F3rias de Sucesso" }), _jsx(TestimonialWarning, {}), _jsx("div", { className: "mb-16" }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-10", children: content.testimonials.map((testi, idx) => (_jsxs("div", { className: `p-8 ${p.surface} ${r.box} relative group border ${p.border} hover:border-${design.secondaryColor}-200 transition-colors`, children: [_jsx("div", { className: `text-6xl absolute -top-4 -left-2 opacity-20 font-serif ${s.text}`, children: "\u201C" }), _jsx("p", { className: "text-lg text-gray-600 mb-8 relative z-10 italic leading-relaxed", children: testi.text }), _jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: `w-12 h-12 flex items-center justify-center font-bold text-white shadow-md ${p.accent} ${r.btn}`, children: testi.name.charAt(0) }), _jsxs("div", { children: [_jsx("div", { className: `font-bold ${p.primary}`, children: testi.name }), _jsx("div", { className: `text-xs font-semibold uppercase tracking-wider ${s.text}`, children: "Paciente Verificado" })] })] })] }, idx))) })] }) }));
};
export const LocationSection = ({ content, design, briefing, layoutVariant = 1 }) => {
    const { p, s, r } = getDesignClasses(design);
    if (!briefing)
        return null;
    const addresses = content.contactAddresses && content.contactAddresses.length > 0
        ? content.contactAddresses
        : (content.contactAddress ? [content.contactAddress] : [briefing.addresses?.[0] || '']);
    const addressCount = addresses.length;
    // Layout 5: Editorial - Clean Minimal
    if (layoutVariant === 5) {
        return (_jsx("section", { id: "location", className: "py-16 px-6 bg-white border-t border-gray-100", children: _jsxs("div", { className: `mx-auto ${addressCount === 1 ? 'max-w-4xl' : 'max-w-6xl'}`, children: [_jsx("h3", { className: "text-center text-xs font-bold uppercase tracking-widest mb-10 text-gray-400", children: "Nossas Unidades" }), _jsx("div", { className: `${addressCount === 1 ? 'w-full' : 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8'}`, children: addresses.map((addr, idx) => (_jsxs("div", { className: `flex flex-col ${addressCount === 1 ? 'text-center' : ''}`, children: [_jsx("p", { className: "text-sm font-bold text-gray-900 mb-2", children: addr }), _jsx(MapEmbed, { address: addr, className: "rounded-none border border-gray-200", heightClass: addressCount === 1 ? "h-64 md:h-96" : "h-64" })] }, idx))) })] }) }));
    }
    // Layout 4: Grid Studio - Brutalist
    if (layoutVariant === 4) {
        return (_jsx("section", { id: "location", className: "border-t-2 border-black", children: _jsx("div", { className: `grid ${addressCount === 1 ? 'grid-cols-1' : 'grid-cols-1 md:grid-cols-2 lg:grid-cols-3'}`, children: addresses.map((addr, idx) => (_jsxs("div", { className: "border-b md:border-b-0 md:border-r border-black p-8 last:border-r-0", children: [_jsxs("h4", { className: "font-bold uppercase mb-4 text-sm", children: ["Unidade ", idx + 1] }), _jsx("p", { className: "font-mono text-sm mb-4 truncate", children: addr }), _jsx(MapEmbed, { address: addr, className: "border-2 border-black", heightClass: addressCount === 1 ? "h-64 md:h-96" : "h-64" })] }, idx))) }) }));
    }
    // Layout 2: Modern - Dark/Gradient
    if (layoutVariant === 2) {
        return (_jsx("section", { id: "location", className: `py-16 px-6 ${p.surfaceDark} relative overflow-hidden`, children: _jsxs("div", { className: `mx-auto relative z-10 ${addressCount === 1 ? 'max-w-5xl' : 'max-w-7xl'}`, children: [_jsx("h3", { className: "text-center text-xl font-bold text-white mb-10", children: "Onde nos encontrar" }), _jsx("div", { className: `${addressCount === 1 ? 'w-full' : addressCount === 2 ? 'flex flex-col md:flex-row justify-center gap-8' : 'grid grid-cols-1 md:grid-cols-3 gap-8'}`, children: addresses.map((addr, idx) => (_jsxs("div", { className: `bg-white/5 p-4 rounded-xl border border-white/10 backdrop-blur-sm ${addressCount === 2 ? 'w-full md:w-1/2 max-w-lg' : ''}`, children: [_jsxs("p", { className: "text-gray-300 text-sm mb-3 flex items-center gap-2", children: [_jsx("span", { className: "text-white", children: "\uD83D\uDCCD" }), " ", addr] }), _jsx(MapEmbed, { address: addr, className: "rounded-lg opacity-80 hover:opacity-100 transition-opacity", heightClass: addressCount === 1 ? "h-64 md:h-96" : "h-64" })] }, idx))) })] }) }));
    }
    // Default / Organic / Classic
    return (_jsx("section", { id: "location", className: `py-16 px-6 ${p.softBg}`, children: _jsxs("div", { className: `mx-auto ${addressCount === 1 ? 'max-w-5xl' : 'max-w-7xl'}`, children: [_jsxs("div", { className: "text-center mb-10", children: [_jsx("h3", { className: `text-2xl font-bold ${p.primary}`, children: "Localiza\u00E7\u00E3o" }), _jsx("div", { className: `w-16 h-1 mx-auto ${s.bg} rounded-full mt-2` })] }), addressCount === 1 ? (
                // Full width single address layout
                _jsxs("div", { className: `bg-white p-6 shadow-sm border ${p.border} ${r.box}`, children: [_jsxs("div", { className: "flex flex-col md:flex-row items-center md:items-start gap-3 mb-4 justify-center", children: [_jsx("div", { className: `mt-1 p-1.5 rounded-full ${s.light} text-${design.secondaryColor}-600`, children: _jsxs("svg", { className: "w-5 h-5", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: [_jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" }), _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M15 11a3 3 0 11-6 0 3 3 0 016 0z" })] }) }), _jsx("p", { className: "text-gray-700 font-medium text-lg text-center md:text-left", children: addresses[0] })] }), _jsx(MapEmbed, { address: addresses[0], className: `${r.box}`, heightClass: "h-64 md:h-96" })] })) : (
                // Grid or Flex for multiple
                _jsx("div", { className: `${addressCount === 2 ? 'flex flex-col md:flex-row justify-center gap-8' : 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8'}`, children: addresses.map((addr, idx) => (_jsxs("div", { className: `bg-white p-4 shadow-sm border ${p.border} ${r.box} ${addressCount === 2 ? 'w-full md:w-1/2 max-w-lg' : ''}`, children: [_jsxs("div", { className: "flex items-start gap-3 mb-4", children: [_jsx("div", { className: `mt-1 p-1.5 rounded-full ${s.light} text-${design.secondaryColor}-600`, children: _jsxs("svg", { className: "w-4 h-4", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: [_jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" }), _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M15 11a3 3 0 11-6 0 3 3 0 016 0z" })] }) }), _jsx("p", { className: "text-gray-700 font-medium", children: addr })] }), _jsx(MapEmbed, { address: addr, className: `${r.box}` })] }, idx))) }))] }) }));
};
export const FooterSection = ({ content, design, briefing, layoutVariant = 1 }) => {
    const { p, s } = getDesignClasses(design);
    if (!briefing)
        return null;
    const addresses = content.contactAddresses && content.contactAddresses.length > 0
        ? content.contactAddresses
        : (content.contactAddress ? [content.contactAddress] : [briefing.addresses?.[0] || '']);
    const Credentials = () => (_jsxs("div", { className: "mt-4 pt-4 border-t border-gray-200/20 text-xs opacity-70 font-mono", children: [_jsx("div", { className: "font-bold", children: "Respons\u00E1vel T\u00E9cnico:" }), _jsx("div", { children: briefing.name }), _jsxs("div", { children: ["CRM/", briefing.crmState || 'UF', " ", briefing.crm || '0000'] }), briefing.rqe && _jsxs("div", { children: ["RQE ", briefing.rqe] })] }));
    if (layoutVariant === 5) {
        return (_jsxs("footer", { id: "contact", className: "py-16 bg-white text-center border-t border-black px-6", children: [_jsx("h2", { className: "font-serif text-2xl mb-4", children: briefing.name }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 max-w-6xl mx-auto mb-8 text-sm", children: [_jsxs("div", { children: [_jsx("h4", { className: "font-bold uppercase tracking-widest text-xs mb-2 text-gray-400", children: "Contato" }), content.contactPhone && (_jsx("p", { children: _jsx("a", { href: `tel:${content.contactPhone.replace(/[^+\d]/g, '')}`, className: "hover:underline", children: content.contactPhone }) })), content.contactEmail && (_jsx("p", { children: _jsx("a", { href: `mailto:${content.contactEmail}`, className: "hover:underline", children: content.contactEmail }) }))] }), addresses.map((addr, idx) => (_jsxs("div", { children: [_jsxs("p", { className: "text-xs uppercase tracking-widest text-gray-400 mb-1 font-bold", children: ["Unidade ", idx + 1] }), _jsx("p", { className: "text-gray-800", children: addr })] }, idx)))] }), _jsxs("div", { className: "text-xs text-gray-400 mb-8", children: ["CRM/", briefing.crmState, " ", briefing.crm, " ", briefing.rqe && `• RQE ${briefing.rqe}`] }), _jsxs("p", { className: "text-sm text-gray-400", children: ["\u00A9 2026 ", briefing.name, ". Todos os direitos reservados."] })] }));
    }
    if (layoutVariant === 4) {
        return (_jsxs("footer", { id: "contact", className: "border-t-4 border-black bg-white text-black", children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2", children: [_jsxs("div", { className: "p-12 border-b md:border-b-0 md:border-r border-black", children: [_jsx("h3", { className: "text-3xl font-black uppercase mb-4", children: briefing.name }), _jsx("p", { className: "font-mono text-sm mb-4", children: briefing.specialty }), _jsxs("div", { className: "text-xs font-mono border-t border-black pt-2", children: ["CRM/", briefing.crmState, " ", briefing.crm, " ", _jsx("br", {}), " ", briefing.rqe && _jsxs(_Fragment, { children: ["RQE ", briefing.rqe] })] })] }), _jsxs("div", { className: "p-12", children: [_jsx("h4", { className: "font-bold uppercase mb-4", children: "Contato & Endere\u00E7o" }), _jsxs("ul", { className: "space-y-2 font-medium", children: [content.contactEmail && (_jsx("li", { children: _jsx("a", { href: `mailto:${content.contactEmail}`, className: "hover:underline", children: content.contactEmail }) })), content.contactPhone && (_jsx("li", { children: _jsx("a", { href: `tel:${content.contactPhone.replace(/[^+\d]/g, '')}`, className: "hover:underline", children: content.contactPhone }) }))] }), _jsx("div", { className: "mt-6 space-y-2", children: addresses.map((addr, idx) => (_jsx("p", { className: "font-mono text-sm", children: addr }, idx))) })] })] }), _jsxs("div", { className: "bg-black text-white p-4 text-center font-mono text-xs uppercase", children: ["Powered by ", _jsx("a", { href: "https://docpage.com.br", target: "_blank", children: "DocPage AI" })] })] }));
    }
    if (layoutVariant === 3) {
        return (_jsxs("footer", { id: "contact", className: `relative pt-24 pb-12 ${p.surface} text-gray-800`, children: [_jsx("div", { className: "absolute top-0 left-0 w-full overflow-hidden leading-none", children: _jsx("svg", { "data-name": "Layer 1", xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 1200 120", preserveAspectRatio: "none", className: "relative block h-[60px] w-[calc(100%+1.3px)] fill-white", children: _jsx("path", { d: "M321.39,56.44c58-10.79,114.16-30.13,172-41.86,82.39-16.72,168.19-17.73,250.45-.39C823.78,31,906.67,72,985.66,92.83c70.05,18.48,146.53,26.09,214.34,3V0H0V27.35A600.21,600.21,0,0,0,321.39,56.44Z" }) }) }), _jsxs("div", { className: "max-w-6xl mx-auto px-6 grid grid-cols-1 md:grid-cols-3 gap-12", children: [_jsxs("div", { children: [_jsx("h3", { className: `text-2xl font-bold mb-4 ${p.primary}`, children: briefing.name }), _jsx("p", { className: "text-gray-600 mb-6", children: "Cuidando de voc\u00EA com aten\u00E7\u00E3o e carinho." }), _jsxs("div", { className: "text-xs text-gray-500 font-medium", children: ["CRM/", briefing.crmState, " ", briefing.crm, " ", _jsx("br", {}), briefing.rqe && `RQE ${briefing.rqe}`] })] }), _jsxs("div", { children: [_jsx("h4", { className: "font-bold mb-4 text-gray-900", children: "Fale Conosco" }), content.contactPhone && (_jsx("p", { className: "text-gray-600 mb-2", children: _jsx("a", { href: `tel:${content.contactPhone.replace(/[^+\d]/g, '')}`, className: "hover:underline", children: content.contactPhone }) })), content.contactEmail && (_jsx("p", { className: "text-gray-600", children: _jsx("a", { href: `mailto:${content.contactEmail}`, className: "hover:underline", children: content.contactEmail }) }))] }), _jsxs("div", { children: [_jsx("h4", { className: "font-bold mb-4 text-gray-900", children: "Endere\u00E7os" }), _jsx("div", { className: "space-y-4", children: addresses.map((addr, idx) => (_jsx("div", { children: _jsx("p", { className: "text-gray-600 text-sm mb-1", children: addr }) }, idx))) })] })] }), _jsxs("div", { className: "text-center mt-12 pt-8 border-t border-gray-200 text-sm text-gray-500", children: ["\u00A9 ", new Date().getFullYear(), " ", briefing.name] })] }));
    }
    // DEFAULT & MODERN
    return (_jsxs("footer", { id: "contact", className: `${p.surfaceDark} text-white py-20 px-6`, children: [_jsxs("div", { className: "max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-4 gap-12 mb-16", children: [_jsxs("div", { className: "col-span-1 md:col-span-2", children: [_jsxs("h3", { className: "text-2xl font-bold mb-6 tracking-tight flex items-center gap-2", children: [_jsx("div", { className: `w-3 h-3 ${s.bg} rounded-full` }), briefing.name] }), _jsx("p", { className: "text-gray-400 max-w-sm mb-8 leading-relaxed", children: "Medicina integrada com foco no seu bem-estar." }), _jsx(Credentials, {})] }), _jsxs("div", { children: [_jsx("h4", { className: `font-bold mb-6 ${s.text} uppercase text-xs tracking-widest`, children: "Contato" }), _jsxs("ul", { className: "space-y-4 text-gray-400", children: [_jsxs("li", { className: "flex items-center gap-3", children: [_jsx("span", { className: "text-white", children: "\u2709" }), content.contactEmail || briefing.contactEmail ? (_jsx("a", { href: `mailto:${content.contactEmail || briefing.contactEmail}`, className: "hover:underline", children: content.contactEmail || briefing.contactEmail })) : (_jsx("span", { children: "-" }))] }), _jsxs("li", { className: "flex items-center gap-3", children: [_jsx("span", { className: "text-white", children: "\u260E" }), content.contactPhone || briefing.contactPhone ? (_jsx("a", { href: `tel:${(content.contactPhone || briefing.contactPhone || '').replace(/[^+\d]/g, '')}`, className: "hover:underline", children: content.contactPhone || briefing.contactPhone })) : (_jsx("span", { children: "-" }))] })] })] }), _jsxs("div", { children: [_jsx("h4", { className: `font-bold mb-6 ${s.text} uppercase text-xs tracking-widest`, children: "Localiza\u00E7\u00E3o" }), _jsx("div", { className: "space-y-6", children: addresses.map((addr, idx) => (_jsx("div", { children: _jsx("p", { className: "text-gray-400 leading-relaxed text-sm mb-2", children: addr }) }, idx))) })] })] }), _jsx("div", { className: "border-t border-gray-800 pt-8 text-center text-gray-500 text-sm", children: _jsx("span", { children: "Powered by DocPage AI" }) })] }));
};
